-- =============================================================================
-- 01_schema.sql -- transactional tables for the tutoring operations system.
--
-- Run as the application user (default: TUTORING), never as SYSTEM.
-- Re-runnable: drops and recreates everything it owns.
--
-- Hours accounting note (read this before changing anything below):
--   Hours are RESERVED against a package when a session is booked, not when it
--   is completed. That is what makes "cancel restores the hours" meaningful and
--   what stops a student with 2 hours left from booking ten sessions. Every
--   movement of hours is a row in PACKAGE_LEDGER; PACKAGES.HOURS_REMAINING is
--   the materialised running balance and must always equal the ledger sum.
--   See docs/design-decisions.md.
-- =============================================================================

SET DEFINE OFF

-- --- drop in reverse dependency order ---------------------------------------
BEGIN
  FOR r IN (
    SELECT table_name
      FROM user_tables
     WHERE table_name IN ('PACKAGE_LEDGER','EVENT_OUTBOX','PAYMENTS',
                          'SESSIONS','PACKAGES','STUDENTS','TUTORS')
     ORDER BY CASE table_name
                WHEN 'PACKAGE_LEDGER' THEN 1
                WHEN 'EVENT_OUTBOX'   THEN 2
                WHEN 'PAYMENTS'       THEN 3
                WHEN 'SESSIONS'       THEN 4
                WHEN 'PACKAGES'       THEN 5
                WHEN 'STUDENTS'       THEN 6
                ELSE 7
              END
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || r.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/

-- =============================================================================
-- TUTORS
-- One row per person who can teach. The business is currently a single tutor,
-- but sessions still hang off a tutor id because the schedule conflict rule is
-- "this tutor cannot be in two places at once" -- not "this student cannot".
-- The tutor row is also the lock target that serialises booking (see
-- PKG_SCHEDULING.book_session).
-- =============================================================================
CREATE TABLE TUTORS (
  TUTOR_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  FULL_NAME   VARCHAR2(120)  NOT NULL,
  IS_ACTIVE   CHAR(1)        DEFAULT 'Y' NOT NULL,
  CREATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_TUTORS       PRIMARY KEY (TUTOR_ID),
  CONSTRAINT CK_TUTORS_ACTIVE CHECK (IS_ACTIVE IN ('Y','N'))
);

-- =============================================================================
-- STUDENTS
-- PREFERRED_LANGUAGE drives which template the reminder function sends.
-- The student row is the lock target that serialises all balance changes for
-- that student, so purchases and reservations can never interleave badly.
-- =============================================================================
CREATE TABLE STUDENTS (
  STUDENT_ID          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  FULL_NAME           VARCHAR2(120)  NOT NULL,
  PARENT_CONTACT      VARCHAR2(200)  NOT NULL,
  PARENT_PHONE        VARCHAR2(40),
  PREFERRED_LANGUAGE  VARCHAR2(2)    DEFAULT 'EN' NOT NULL,
  IS_ACTIVE           CHAR(1)        DEFAULT 'Y'  NOT NULL,
  ACCESS_CODE         VARCHAR2(12),
  CREATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_STUDENTS         PRIMARY KEY (STUDENT_ID),
  CONSTRAINT CK_STUDENTS_LANG    CHECK (PREFERRED_LANGUAGE IN ('EN','ES')),
  CONSTRAINT CK_STUDENTS_ACTIVE  CHECK (IS_ACTIVE IN ('Y','N')),
  CONSTRAINT CK_STUDENTS_CONTACT CHECK (PARENT_CONTACT LIKE '%@%.%')
);

CREATE UNIQUE INDEX UX_STUDENTS_ACCESS_CODE ON STUDENTS (ACCESS_CODE);

-- =============================================================================
-- PACKAGES
-- A block of prepaid hours. HOURS_REMAINING is the materialised balance; the
-- CHECK constraint below is the last line of defence for the invariant the
-- whole project is built to protect -- it can never go negative, and no amount
-- of application bugs or concurrent sessions can make it so.
-- =============================================================================
CREATE TABLE PACKAGES (
  PACKAGE_ID       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  STUDENT_ID       NUMBER         NOT NULL,
  HOURS_PURCHASED  NUMBER(6,2)    NOT NULL,
  HOURS_REMAINING  NUMBER(6,2)    NOT NULL,
  PRICE            NUMBER(10,2)   NOT NULL,
  PURCHASED_DATE   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  EXPIRES_ON       DATE,
  STATUS           VARCHAR2(20)   DEFAULT 'ACTIVE' NOT NULL,
  CREATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PACKAGES          PRIMARY KEY (PACKAGE_ID),
  CONSTRAINT FK_PACKAGES_STUDENT  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (STUDENT_ID),
  CONSTRAINT CK_PACKAGES_STATUS   CHECK (STATUS IN ('ACTIVE','EXHAUSTED','EXPIRED','REFUNDED')),
  CONSTRAINT CK_PACKAGES_PURCH    CHECK (HOURS_PURCHASED > 0),
  CONSTRAINT CK_PACKAGES_PRICE    CHECK (PRICE >= 0),
  -- The invariant. Never remove this to "fix" a failing test.
  CONSTRAINT CK_PACKAGES_REMAIN   CHECK (HOURS_REMAINING >= 0),
  CONSTRAINT CK_PACKAGES_NO_OVER  CHECK (HOURS_REMAINING <= HOURS_PURCHASED)
);

-- Supports the FIFO scan in PKG_BILLING.reserve_hours.
CREATE INDEX IX_PACKAGES_FIFO ON PACKAGES (STUDENT_ID, STATUS, PURCHASED_DATE, PACKAGE_ID);

-- =============================================================================
-- PAYMENTS
-- Two shapes:
--   * package purchase  -> PACKAGE_ID set, APPLIED_FLAG 'Y' on creation
--   * pay-per-session   -> PACKAGE_ID null, APPLIED_FLAG 'N' until a session
--                          consumes it (SESSIONS.PAYMENT_ID)
-- =============================================================================
CREATE TABLE PAYMENTS (
  PAYMENT_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  STUDENT_ID    NUMBER        NOT NULL,
  PACKAGE_ID    NUMBER,
  AMOUNT        NUMBER(10,2)  NOT NULL,
  PAID_DATE     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  METHOD        VARCHAR2(20)  NOT NULL,
  APPLIED_FLAG  CHAR(1)       DEFAULT 'N' NOT NULL,
  NOTES         VARCHAR2(400),
  CREATED_AT    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_PAYMENTS         PRIMARY KEY (PAYMENT_ID),
  CONSTRAINT FK_PAYMENTS_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (STUDENT_ID),
  CONSTRAINT FK_PAYMENTS_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGES (PACKAGE_ID),
  CONSTRAINT CK_PAYMENTS_AMOUNT  CHECK (AMOUNT > 0),
  CONSTRAINT CK_PAYMENTS_METHOD  CHECK (METHOD IN ('CASH','ZELLE','VENMO','CARD','TRANSFER','OTHER')),
  CONSTRAINT CK_PAYMENTS_APPLIED CHECK (APPLIED_FLAG IN ('Y','N'))
);

CREATE INDEX IX_PAYMENTS_UNAPPLIED ON PAYMENTS (STUDENT_ID, APPLIED_FLAG, PAID_DATE);

-- =============================================================================
-- SESSIONS
-- END_TIME is a virtual column so the overlap predicate stays readable and can
-- be indexed. PACKAGE_ID records the package the hours came from first; when a
-- booking is split across two packages the full detail lives in PACKAGE_LEDGER.
-- =============================================================================
CREATE TABLE SESSIONS (
  SESSION_ID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  STUDENT_ID        NUMBER        NOT NULL,
  TUTOR_ID          NUMBER        DEFAULT 1 NOT NULL,
  PACKAGE_ID        NUMBER,
  PAYMENT_ID        NUMBER,
  START_TIME        TIMESTAMP     NOT NULL,
  DURATION_MINUTES  NUMBER(4)     NOT NULL,
  END_TIME          TIMESTAMP     GENERATED ALWAYS AS
                      (START_TIME + NUMTODSINTERVAL(DURATION_MINUTES,'MINUTE')) VIRTUAL,
  STATUS            VARCHAR2(20)  DEFAULT 'REQUESTED' NOT NULL,
  HOURS_RESERVED    NUMBER(6,2)   DEFAULT 0 NOT NULL,
  NOTES             VARCHAR2(400),
  CREATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  UPDATED_AT        TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CANCELLED_AT      TIMESTAMP,
  COMPLETED_AT      TIMESTAMP,
  CONSTRAINT PK_SESSIONS          PRIMARY KEY (SESSION_ID),
  CONSTRAINT FK_SESSIONS_STUDENT  FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (STUDENT_ID),
  CONSTRAINT FK_SESSIONS_TUTOR    FOREIGN KEY (TUTOR_ID)   REFERENCES TUTORS (TUTOR_ID),
  CONSTRAINT FK_SESSIONS_PACKAGE  FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGES (PACKAGE_ID),
  CONSTRAINT FK_SESSIONS_PAYMENT  FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENTS (PAYMENT_ID),
  CONSTRAINT CK_SESSIONS_STATUS   CHECK (STATUS IN
                      ('REQUESTED','CONFIRMED','COMPLETED','CANCELLED','LATE_CANCELLED')),
  CONSTRAINT CK_SESSIONS_DURATION CHECK (DURATION_MINUTES BETWEEN 30 AND 300
                                     AND MOD(DURATION_MINUTES,15) = 0),
  CONSTRAINT CK_SESSIONS_RESERVED CHECK (HOURS_RESERVED >= 0)
);

-- The overlap check in book_session drives off this index.
CREATE INDEX IX_SESSIONS_TUTOR_WINDOW ON SESSIONS (TUTOR_ID, STATUS, START_TIME);
CREATE INDEX IX_SESSIONS_STUDENT      ON SESSIONS (STUDENT_ID, START_TIME);
-- Supports the nightly reminder sweep.
CREATE INDEX IX_SESSIONS_UPCOMING     ON SESSIONS (STATUS, START_TIME);

-- =============================================================================
-- PACKAGE_LEDGER
-- Append-only record of every movement of hours. This table is the reason the
-- "cancelled twice" bug cannot exist: the unique constraint makes a second
-- RELEASE for the same (session, package) pair a constraint violation, not a
-- silent double credit. PACKAGES.HOURS_REMAINING is derived from these rows and
-- the test suite asserts the two agree.
--
--   PURCHASE  +hours, no session
--   RESERVE   -hours, on booking
--   RELEASE   +hours, on an on-time cancellation only
--
-- COMPLETED and LATE_CANCELLED deliberately have no ledger entry: the hours
-- stay reserved, which is exactly what "consumed" and "forfeited" mean here.
-- =============================================================================
CREATE TABLE PACKAGE_LEDGER (
  LEDGER_ID    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  PACKAGE_ID   NUMBER        NOT NULL,
  SESSION_ID   NUMBER,
  ENTRY_TYPE   VARCHAR2(20)  NOT NULL,
  HOURS_DELTA  NUMBER(6,2)   NOT NULL,
  CREATED_AT   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT PK_LEDGER         PRIMARY KEY (LEDGER_ID),
  CONSTRAINT FK_LEDGER_PACKAGE FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGES (PACKAGE_ID),
  CONSTRAINT FK_LEDGER_SESSION FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (SESSION_ID),
  CONSTRAINT CK_LEDGER_TYPE    CHECK (ENTRY_TYPE IN ('PURCHASE','RESERVE','RELEASE')),
  -- A purchase has no session; a reserve/release always does.
  CONSTRAINT CK_LEDGER_SESSION CHECK (
       (ENTRY_TYPE = 'PURCHASE' AND SESSION_ID IS NULL)
    OR (ENTRY_TYPE IN ('RESERVE','RELEASE') AND SESSION_ID IS NOT NULL)),
  CONSTRAINT CK_LEDGER_SIGN    CHECK (
       (ENTRY_TYPE = 'PURCHASE' AND HOURS_DELTA > 0)
    OR (ENTRY_TYPE = 'RESERVE'  AND HOURS_DELTA < 0)
    OR (ENTRY_TYPE = 'RELEASE'  AND HOURS_DELTA > 0))
);

-- The double-restore guard. One RESERVE and at most one RELEASE per
-- (session, package). Nulls in SESSION_ID mean PURCHASE rows are unconstrained.
CREATE UNIQUE INDEX UX_LEDGER_SESSION_ENTRY
  ON PACKAGE_LEDGER (SESSION_ID, PACKAGE_ID, ENTRY_TYPE);

CREATE INDEX IX_LEDGER_PACKAGE ON PACKAGE_LEDGER (PACKAGE_ID);

-- =============================================================================
-- EVENT_OUTBOX
-- The API layer never publishes to Service Bus directly. Business procedures
-- write an outbox row in the same transaction as the state change, and a
-- background publisher drains it. If the transaction rolls back the event
-- disappears with it, so the database stays the source of truth.
-- =============================================================================
CREATE TABLE EVENT_OUTBOX (
  EVENT_ID        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  EVENT_TYPE      VARCHAR2(60)  NOT NULL,
  AGGREGATE_TYPE  VARCHAR2(30)  NOT NULL,
  AGGREGATE_ID    NUMBER        NOT NULL,
  PAYLOAD         CLOB          NOT NULL,
  CREATED_AT      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  PUBLISHED_FLAG  CHAR(1)       DEFAULT 'N' NOT NULL,
  PUBLISHED_AT    TIMESTAMP,
  ATTEMPT_COUNT   NUMBER(4)     DEFAULT 0 NOT NULL,
  LAST_ERROR      VARCHAR2(2000),
  CONSTRAINT PK_OUTBOX           PRIMARY KEY (EVENT_ID),
  CONSTRAINT CK_OUTBOX_FLAG      CHECK (PUBLISHED_FLAG IN ('N','Y')),
  CONSTRAINT CK_OUTBOX_JSON      CHECK (PAYLOAD IS JSON),
  CONSTRAINT CK_OUTBOX_AGGREGATE CHECK (AGGREGATE_TYPE IN ('SESSION','PACKAGE','STUDENT','PAYMENT'))
);

-- The publisher's claim query: unpublished rows, oldest first.
CREATE INDEX IX_OUTBOX_UNPUBLISHED ON EVENT_OUTBOX (PUBLISHED_FLAG, EVENT_ID);

-- --- the single tutor -------------------------------------------------------
INSERT INTO TUTORS (TUTOR_ID, FULL_NAME) VALUES (1, 'Primary Tutor');
COMMIT;

PROMPT Schema created.
